### ISSUE TITLE
Scroll to highlighted actions

### ISSUE THREAD

**Issue by jpnurmi** [TNorbury/command_palette#19]
Would it be possible to call [RenderObject.showOnScreen()](https://api.flutter.dev/flutter/rendering/RenderObject/showOnScreen.html) for the highlighted action to bring it into the viewport while navigating up and down?

[command_palette.webm](https://user-images.githubusercontent.com/140617/197468042-cd9e316f-3e33-4286-a6ee-636f98ea06af.webm)

```dart
import 'package:command_palette/command_palette.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: CommandPalette(
          actions: [
            for (var i = 0; i < 20; ++i)
              CommandPaletteAction(
                label: 'Command $i',
                description: 'Description $i...',
                actionType: CommandPaletteActionType.single,
                onSelect: () {},
              ),
          ],
          child: SizedBox.shrink(),
        ),
      ),
    ),
  );
}
```

**Comment by TNorbury** [comment]
Hi @jpnurmi, yeah, hoping to tackle this issue soon!

**Comment by TNorbury** [comment]
Ok, I've been playing around with this, and got a solution that somewhat works doing this:
```dart
class _ActionItemWrapper extends StatefulWidget {
  final bool isHighlighted;
  final Widget child;
  const _ActionItemWrapper({
    Key? key,
    required this.isHighlighted,
    required this.child,
  }) : super(key: key);

  @override
  State<_ActionItemWrapper> createState() => _ActionItemWrapperState();
}

class _ActionItemWrapperState extends State<_ActionItemWrapper> {
  @override
  void didUpdateWidget(covariant _ActionItemWrapper oldWidget) {
    super.didUpdateWidget(oldWidget);

    if (!oldWidget.isHighlighted && widget.isHighlighted) {
      WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
        final ro = context.findRenderObject();
        ro?.showOnScreen();
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}
```

It works well with a small selection of actions, but once the number of actions gets so big (starting at around 30, though the number will depend on palette height), there are some issues related to not all the items getting built (due to being in a ListView). This creates an issue where in one of the two following cases, the scroll to item will not work:
1. Going from the first to last, or last to first.
2. Having an item selected, then scrolling away (i.e. with mouse wheel), then using the arrow keys to navigate.

This problem can be solved by using a SingleChildListView with a Column, but this creates performance issues with really long lists (e.g. >1000), which I suppose isn't a big deal, cause realistically I don't think anyone would ever have that many items...

I'm gonna do a little more research to see if there are any alternative methods (perhaps using a SliverList), but I think the SingleChildListView will be what I end up going with, and if it ends up being a performance issue for some users, a better solution will be found.

**Comment by karniv00l** [comment]
There's a project that have a command palette: https://github.com/KRTirtho/wives, maybe it will help, but personally I'm not a big fun of how the scrolling feels

**Comment by TNorbury** [comment]
Thanks everyone for their patience on this. I've fixed the issue and a new release has been pushed to pub.dev 🎯
